### ISSUE TITLE
SlowCheetah doesn't play well with nuget pack of csproj projects

### ISSUE THREAD

**Issue by morten-leerhoy** [Microsoft/slow-cheetah#136]
To reproduce:
1. Create a sample mvc project in VS2017
2. Add latest SlowCheetah nuget package (tried a lot of different versions)
3. run ```nuget pack <nameofproject>.csproj ``` from cmd prompt

you should get a bunch of warnings that xxx.file is not added because the package already contains file 'content'.

the culprit seems to be this part of the Microsoft.VisualStudio.SlowCheetah.targets
```
<Content>
    <TransformOnBuild>false</TransformOnBuild>
    <Link></Link>
</Content>
```

commenting out this entry enables nuget pack to complete - but the transformations obviously fails, on subsequent builds.

**Comment by davilimap** [comment]
More info on this [here](https://stackoverflow.com/questions/33486956/nuget-pack-on-a-web-project-renames-all-content-files-to-content). Seems to be a problem with nuget and web projects. Workaround would be specifying the package strucure so Nuget doesn't rename the Content files when packing

**Comment by morten-leerhoy** [comment]
Ah - thanks for the info @davilimap

**Comment by ryno1234** [comment]
@morten-leerhoy , I don't see how this is a solution (using a .nuspec instead of a .csproj), when .csproj is a supported format for input by NuGet pack. I'm having this same issue and just switching everything to nuspecs and explicitly defining the content doesn't seem reasonable considering .csprojs should be supported.
