### ISSUE TITLE
Transform does not work anymore

### ISSUE THREAD

**Issue by schweinsbauch** [Microsoft/slow-cheetah#149]
After updating from 3.0.61 to 3.1.66 transforming my nlog.config does not work anymore, while transforming the app.config still works. After downgrading to 3.0.61 everything works as expected again. 

Here an excerpt of the .csproj:
 `   <None Include="NLog.config">
      <TransformOnBuild>true</TransformOnBuild>
      <SubType>Designer</SubType>
    </None>
    <None Include="NLog.Debug.config">
      <DependentUpon>NLog.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
      <SubType>Designer</SubType>
    </None>
    <None Include="NLog.Debug_Production.config">
      <DependentUpon>NLog.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
    <None Include="NLog.Production.config">
      <DependentUpon>NLog.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
    <None Include="NLog.Release.config">
      <DependentUpon>NLog.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
      <SubType>Designer</SubType>
    </None>`

Am I missing something?

**Comment by bwgit** [comment]
I had a similar issue after upgrading - turns out I had another NLog.config (plus related transform config) in another project that my exe was referencing - within that second project the NLog.config was also set to copy always (not sure if that was a contributing factor).

Once I removed the NLog.config from the referenced project (it wasn't needed) - the transforms worked as normal.

I also noted the transformed NLog.config in my obj folder of the exe looked correct - so went looking for where the NLog.config copied to my bin folder was coming from.

**Comment by schweinsbauch** [comment]
@bwgit thank you for your answer.

> Once I removed the NLog.config from the referenced project (it wasn't needed) - the transforms worked as normal.

This solves the problem for me - thank you
