### ISSUE TITLE
Version 3.2.20 is not copying transforms to output folder

### ISSUE THREAD

**Issue by Kaelum** [microsoft/slow-cheetah#182]
I upgraded from 3.1.66 to 3.2.20 today, and none of the transformed files are being copied to the output folder.  Reverting back to 3.1.66 fixes this.

#169 is what has broken this

**Comment by Kaelum** [comment]
The problem that #166 has created is that it changed the default behavior that people have been using for several years.  Every single project that depended on this default behavior, is now broken.  I wasted over 4 hours trying to figure out why an application all of a sudden stopped working.

All #166 required was to ensure that Build Action "Do not copy" was working properly, and to set that in projects as needed.  SlowCheetah is being used in so many different ways, for so many different types of projects, all of which have different folder structures, and no one performed any regression tests to determine what affect this would have?

**Comment by hsalazarl** [comment]
- Transforming does not work for app.config.
- Preview transform does not work.
- Setting "Copy Always" to app.config does not transform the files (.Debug.config, .Release.config) to the output dir.

**Comment by Kaelum** [comment]
Ok, the code changes for #166 and #169 have completely broken SlowCheetah and need to be removed.  It doesn't even work by following the documentation exactly as written.  This is the biggest screw-up that I've ever seen.  HOW WAS THIS RELEASED WITHOUT ANY REGRESSION TESTING?

**Comment by kernelcoredump** [comment]
What I've found in using SlowCheetah on our ASP.NET MVC5 projects is that the fix from #169 to address issue #166 is appropriate, but there's another separate issue with SC itself.

Issue #166 was putting the transformed files into the _bin_ folder, which is not correct for an ASP.NET MVC5 application.  For ASP.NET MVC5 apps, the intent is to put the transformed files into the "publish" location, as specified by publish profiles (pubxml).

I traced through the build and publish process and saw that during the build phase, SC is first putting the transformed files into the _obj/$(Configuration)_ folder.  It is also at this phase where it removes the source files from the internal MSBuild _@(ContentWithPath)_ collection and substitutes into the collection the items that are in the _obj/$(Configuration)_ location.  I think the intent of the substitution within the collection is such that during the publishing phase, the collection is emitted to the publish location.

The problem is that during the publish phase, the publish collection is re-initiated using the internal MSBuild _@(Content)_ collection, as seen in the _Microsoft.Web.Publishing.*.Targets_, and the _@(ContentWithPath)_ collection is ignored.  Because the _@(Content)_ collection is used, it essentially puts the original non-transformed files into the publish location.

I use the following workaround in my publish profiles to accommodate the discrepancy:
```
  <PropertyGroup>
    <CopyAllFilesToSingleFolderForMsdeployDependsOn>
      CollectCustomFiles;
      $(CopyAllFilesToSingleFolderForMsdeployDependsOn);
    </CopyAllFilesToSingleFolderForMsdeployDependsOn>
  </PropertyGroup>
  <Target Name="CollectCustomFiles">
    <ItemGroup>
      <FilesForPackagingFromProject Remove="@(ContentWithTargetPath->'%(OriginalItemSpec)')" />
      <FilesForPackagingFromProject Include="@(ContentWithTargetPath)" Exclude="@(AppConfigWithTargetPath)">
        <DestinationRelativePath>%(ContentWithTargetPath.TargetPath)</DestinationRelativePath>
      </FilesForPackagingFromProject>
    </ItemGroup>
  </Target>
```

**Comment by davilimap** [comment]
Version 3.2.26 fixes this

**Comment by andrewwburns** [comment]
Yeah, I'm still seeing this behaviour with version 3.2.26. If I build and publish in Visual Studio it works fine, but using msbuild just copies the untransformed files. I have recently both a) upgraded the version of Slowcheetah that I'm using, and b) converted my projects over to using Package References.

**Comment by DavidMtbg** [comment]
@andrewwburns, this is a bit old, but in case someone else has that issue since you mentioned moving to PackageReferences: you may need to use this workaround to get SlowCheetah to work with those: https://blog.vitaliitylyk.com/slowcheetah-and-nuget-packagereference-format/
