### ISSUE TITLE
Transformations doesn't work properly in Microsoft Add-in Manifest xml file

### ISSUE THREAD

**Issue by pablocastrobarbosa** [microsoft/slow-cheetah#188]
I think it's because it has an inner tag "<versionOverrides xmlns =" http://schemas.microsoft.com/office/taskpaneappversionoverrides "xsi: type =" VersionOverridesV1_0 ">" because the transformation does not work for it.

[WordWebAddIn1.xml.txt](https://github.com/microsoft/slow-cheetah/files/3188543/WordWebAddIn1.xml.txt)
[WordWebAddIn1.Debug.xml.txt](https://github.com/microsoft/slow-cheetah/files/3188545/WordWebAddIn1.Debug.xml.txt)

**Comment by davilimap** [comment]
This seems to be because of that tag. It seems to set it to override the transform value and always keep the original (as you can see by the ov:Override tag in the transformed file.
This is either an error with XDT (the Xml transformation engine used by SlowCheetah) or with the schema you are using. Unfortunately, SlowCheetah cannot fix either of these.
