### ISSUE TITLE
Running 2.5.48.45331, VS 2017 complains I don't have the correct version. 

### ISSUE THREAD

**Issue by linusnikander** [Microsoft/slow-cheetah#29]
![image](https://cloud.githubusercontent.com/assets/2018422/25846428/10f39fdc-34b2-11e7-8960-c3a910d10e14.png)

![image](https://cloud.githubusercontent.com/assets/2018422/25846440/1b761854-34b2-11e7-8c60-f1c414e1e4b0.png)

![image](https://cloud.githubusercontent.com/assets/2018422/25846449/258af3fa-34b2-11e7-8681-92e069674245.png)

I installed it by searching for it in Extensions and Updates if that matters, not through the cmd-line package manager.

**Comment by Kveey** [comment]
I agree. I have the same issue. Also the transformations are not working.  Not sure if this could be the reason behind it.

**Comment by davilimap** [comment]
@linusnikander Do you have the [SlowCheetah NuGet package](https://www.nuget.org/packages/SlowCheetah) installed? This is necessary for build-time transformations, The extension only cointais UI for adding and previewing transformations. If you do have the package installed, see [here](https://github.com/Microsoft/slow-cheetah/blob/master/doc/update.md) for info about updating from older versions of SlowCheetah. The next version of the package should automate this installation.
@Kveey This is probably not the reason for transform not to be working. If this is a problem for you, open another issue explaining what happens when you try to transform and we'll investigate it further.

**Comment by linusnikander** [comment]
ah, that might be it. Didn't realise the UI came without it, a bit non-intuitive. Now that i've got it up and running, one question: When I run it locally, should it be running using the selected configuration within VS or do I have to deploy in order for it to work it's magic? The reason I'm asking is because I can't seem to get it to work (I'm primarily trying locally within VS though)

**Comment by davilimap** [comment]
If you are attempting to transform a `web.config` file, you need to deploy for SlowCheetah to properly transform this. This is because web projects use the in-place config file instead of one in the output folder, which is where SlowCheetah places its transformed files.

**Comment by davilimap** [comment]
@linusnikander I missed the rest of your comment. I suggest commenting again and not editing your previous comments so notifications appear for everyone involved in the issue.
Anyways, as I mentioned, when you build a web project, it uses the native `web.config` file. That is, the original copy of it in you project and currently SlowCheetah does not transform that.
In terms of publishing to AWS, what transform file are you using? It should be `web.Release.config` as that is the one that is generally used to publish. If you are using that, can you post the relevant contents of the original, the transform and the resulting file? Is it transforming other parts of the file?

**Comment by jviau** [comment]
Closing in favor of #55 for tracking the web.config not transforming on F5
